nuget pack "./Utilities/Utilities.nuspec"
nuget pack "./Utilities.AI/Utilities.AI.nuspec"
nuget pack "./Utilities.Caching/Utilities.Caching.nuspec"
nuget pack "./Utilities.CodeGen/Utilities.CodeGen.nuspec"
nuget pack "./Utilities.Compression/Utilities.Compression.nuspec"
nuget pack "./Utilities.Configuration/Utilities.Configuration.nuspec"
nuget pack "./Utilities.DataMapper/Utilities.DataMapper.nuspec"
nuget pack "./Utilities.DataTypes/Utilities.DataTypes.nuspec"
nuget pack "./Utilities.Encryption/Utilities.Encryption.nuspec"
nuget pack "./Utilities.Environment/Utilities.Environment.nuspec"
nuget pack "./Utilities.Error/Utilities.Error.nuspec"
nuget pack "./Utilities.Events/Utilities.Events.nuspec"
nuget pack "./Utilities.Exchange/Utilities.Exchange.nuspec"
nuget pack "./Utilities.FileFormats/Utilities.FileFormats.nuspec"
nuget pack "./Utilities.IO/Utilities.IO.nuspec"
nuget pack "./Utilities.IoC/Utilities.IoC.nuspec"
nuget pack "./Utilities.LDAP/Utilities.LDAP.nuspec"
nuget pack "./Utilities.Math/Utilities.Math.nuspec"
nuget pack "./Utilities.Media/Utilities.Media.nuspec"
nuget pack "./Utilities.ORM/Utilities.ORM.nuspec"
nuget pack "./Utilities.Profiler/Utilities.Profiler.nuspec"
nuget pack "./Utilities.Random/Utilities.Random.nuspec"
nuget pack "./Utilities.Reflection/Utilities.Reflection.nuspec"
nuget pack "./Utilities.SQL/Utilities.SQL.nuspec"
nuget pack "./Utilities.Validation/Utilities.Validation.nuspec"
nuget pack "./Utilities.Web/Utilities.Web.nuspec"

FOR %%A IN (*.nupkg) DO nuget push %%A