var dir_ff08ba1239df36e241ac9aa57b32dcdc =
[
    [ "ArrayExtensions.cs", "_array_extensions_8cs.html", null ],
    [ "CacheExtensions.cs", "_cache_extensions_8cs.html", null ],
    [ "ConcurrentBagExtensions.cs", "_concurrent_bag_extensions_8cs.html", null ],
    [ "ConcurrentDictionary.cs", "_concurrent_dictionary_8cs.html", null ],
    [ "DateTimeExtensions.cs", "_date_time_extensions_8cs.html", "_date_time_extensions_8cs" ],
    [ "DelegateExtensions.cs", "_delegate_extensions_8cs.html", null ],
    [ "ExceptionExtensions.cs", "_exception_extensions_8cs.html", null ],
    [ "GenericObjectExtensions.cs", "_generic_object_extensions_8cs.html", null ],
    [ "ICollectionExtensions.cs", "_i_collection_extensions_8cs.html", null ],
    [ "IComparableExtensions.cs", "_i_comparable_extensions_8cs.html", null ],
    [ "IDictionaryExtensions.cs", "_i_dictionary_extensions_8cs.html", null ],
    [ "IEnumerableExtensions.cs", "_i_enumerable_extensions_8cs.html", null ],
    [ "MatchCollectionExtensions.cs", "_match_collection_extensions_8cs.html", null ],
    [ "MathExtensions.cs", "_math_extensions_8cs.html", null ],
    [ "PermutationExtensions.cs", "_permutation_extensions_8cs.html", null ],
    [ "PredicateExtensions.cs", "_predicate_extensions_8cs.html", null ],
    [ "ProcessExtensions.cs", "_process_extensions_8cs.html", null ],
    [ "ReflectionExtensions.cs", "_reflection_extensions_8cs.html", "_reflection_extensions_8cs" ],
    [ "StackTraceExtensions.cs", "_stack_trace_extensions_8cs.html", null ],
    [ "StreamExtensions.cs", "_stream_extensions_8cs.html", null ],
    [ "StringExtensions.cs", "_data_types_2_extension_methods_2_string_extensions_8cs.html", "_data_types_2_extension_methods_2_string_extensions_8cs" ],
    [ "TimeSpanExtensions.cs", "_time_span_extensions_8cs.html", null ],
    [ "TypeConversionExtensions.cs", "_type_conversion_extensions_8cs.html", null ],
    [ "ValueTypeExtensions.cs", "_value_type_extensions_8cs.html", "_value_type_extensions_8cs" ]
];