var namespace_utilities_1_1_o_r_m_1_1_manager_1_1_query_provider_1_1_default_1_1_s_q_l_server =
[
    [ "SQLServerGenerator", "class_utilities_1_1_o_r_m_1_1_manager_1_1_query_provider_1_1_default_1_1_s_q_l_server_1_1_s_q_l_server_generator.html", "class_utilities_1_1_o_r_m_1_1_manager_1_1_query_provider_1_1_default_1_1_s_q_l_server_1_1_s_q_l_server_generator" ],
    [ "SQLServerQueryProvider", "class_utilities_1_1_o_r_m_1_1_manager_1_1_query_provider_1_1_default_1_1_s_q_l_server_1_1_s_q_l_server_query_provider.html", "class_utilities_1_1_o_r_m_1_1_manager_1_1_query_provider_1_1_default_1_1_s_q_l_server_1_1_s_q_l_server_query_provider" ]
];