// This file is used by Code Analysis to maintain SuppressMessage attributes that are applied to
// this project. Project-level suppressions either have no target or are given a specific target and
// scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIf")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfDefault")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfNotDefault")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfNotNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfNotNullOrDBNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfNullOrDBNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfNotNullOrEmpty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0143:Cannot resolve symbol in text argument", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.DataTypes.ExtensionMethods.GenericObjectExtensions.ThrowIfNullOrEmpty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0026:Possible unassigned object created by 'new'", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.IO.Messaging.Default.DefaultFormatter.Create")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0026:Possible unassigned object created by 'new'", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ORM.Manager.Mapper.Manager.Create")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0026:Possible unassigned object created by 'new'", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ORM.Manager.QueryProvider.Manager.Create")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0026:Possible unassigned object created by 'new'", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ORM.Manager.Schema.Manager.Create")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0026:Possible unassigned object created by 'new'", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ORM.Manager.Session.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0026:Possible unassigned object created by 'new'", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ORM.Manager.Session.Create")]